### ISSUE TITLE
German Translation 

### ISSUE THREAD

**Issue by derhelle** [DiedB/Homey-TeslaEnergy#1]
Hi there,

I would like to help translate the App into German.

BTW Nice Work!

regards Helle

**Comment by DiedB** [comment]
```
{
	"Powerwall SoC": "PowerWall Verbrauch",
	"Powerwall SoC percentage": "PowerWall %",
	"Grid consumption": "Netzbezug",
	"Home consumption": "Hausverbrauch",
	"Solar production": "Solarenergie",
	"Please enter your Tesla Powerwall IP address:": "Bitte geben Sie die Tesla Powerwall IP Adressen ein:",
	"IP address": "IP Adresse",
	"Connect": "Verbinden"
}
```

**Comment by ghost** [comment]
It should be `Powerwall IP Addresse` for the third-to-last entity as it's a singular IP address in the English version.

Also, I'll open a pull request for this as I've seen that hasn't been done yet.

**Comment by DiedB** [comment]
Thanks! I changed the app to support the translations and added a Dutch translation as well.

Can you let me know if everything works in this version? https://homey.app/a/com.tesla.energy/test/

**Comment by DiedB** [comment]
Hey! I integrated the German translations into the test version of the app a few months ago. Tesla updated their Backup Gateways to require authentication with the new firmware, so I made a new version.

Could you update the app to https://homey.app/a/com.tesla.energy/test/ and let me know whether it keeps working for you? Also, are there any places in the app where German translations are missing now?
