### ISSUE TITLE
After login error message: Empty 'data' property"

### ISSUE THREAD

**Issue by powerklash** [DiedB/Homey-TeslaEnergy#10]
b9c16d4b-8396-4175-acaa-446a3a5a153b

After login the error message comes out

**Comment by ghost** [comment]
I got the same error message - using the beta app and homey pro (2023).

**Comment by ghost** [comment]
@powerklash / @DiedB easy fix to quickly work around this - just need to add an id into the data payload when adding the device (i used the sitename) - managed to make it work locally, happy to provide a PR

**Comment by DiedB** [comment]
Would be great, thanks in advance!

**Comment by powerklash** [comment]
> @powerklash / @DiedB easy fix to quickly work around this - just need to add an id into the data payload when adding the device (i used the sitename) - managed to make it work locally, happy to provide a PR

Can you show me your example of where you put the ID? Thanks

**Comment by jco-d** [comment]
this line here: https://github.com/DiedB/Homey-TeslaEnergy/blob/438d6601b2e38f29dbfbaf0f9cad18b4371c5f48/drivers/tesla-backup-gateway/driver.js#L31

basically by making it like this fixed it for me:

`data: {
   id: siteName,
}`

**Comment by ghost** [comment]
this line here: https://github.com/DiedB/Homey-TeslaEnergy/blob/438d6601b2e38f29dbfbaf0f9cad18b4371c5f48/drivers/tesla-backup-gateway/driver.js#L31

basically by making it like this fixed it for me:

`data: {
   id: siteName,
}`

sorry, haven't had time to sort a PR yet

**Comment by ghost** [comment]
> Would be great, thanks in advance!

hey - sorry, can't create a PR as I can't branch etc. - have to fully fork - I posted the fix above though.

**Comment by jdotcole** [comment]
> > Would be great, thanks in advance!
> 
> hey - sorry, can't create a PR as I can't branch etc. - have to fully fork - I posted the fix above though.

forked and pushed fix

**Comment by DiedB** [comment]
Could you give https://homey.app/a/com.tesla.energy/test/ a try and let me know if it works?
