### ISSUE TITLE
With version 1.2.x don't work connect button

### ISSUE THREAD

**Issue by diapolon** [DiedB/Homey-TeslaEnergy#13]
Hi, 
i tried new version 1.20 and 1.2.1 but when i try to add device, after insert ip address, when i click to connect nothing appear

**Comment by diapolon** [comment]
1.2.2 work correctly!
A suggestion, isn't use of kW better than w?

**Comment by DiedB** [comment]
Good to hear! That's a Homey thing, the default power capability is expressed in watts. It's on Athom to make that configurable, or auto-scale the numbers if they get bigger.
