### ISSUE TITLE
Improvement: add the battery percentage in the batt tab

### ISSUE THREAD

**Issue by alechenne** [DiedB/Homey-TeslaEnergy#4]
Could you also add the battery percentage not only on the measures tabl of the device but also in the battery tab (device's tab which is showing a battery with an indicateur of the level in %; in that case it could be easely montored (for example in the power/battery tab of the Homey app, or with the App Battery Monitor, ...)

**Comment by DiedB** [comment]
I have added support in the newest test version, could you try it and let me know whether it works?

I am also wondering if Homey doesn't give any warnings when the battery goes below a certain threshold.

**Comment by alechenne** [comment]
> I have added support in the newest test version, could you try it and let me know whether it works?
> 
> I am also wondering if Homey doesn't give any warnings when the battery goes below a certain threshold.

Did you put the new test version to the same previous link -> https://homey.app/a/com.tesla.energy/test/? If yes, I deinstalled the current official version, installed this (1v1.1.2 experimental) but I don't see the battery tab; the mesaures tab (include the batt level) is ok and running well (updated every 5 sec).

Regarding your the question, I'm not sure as low batt don't appear evry day. But you're certainly right because, before I ask since manymonth I had created a virtual device Powerwall and copy the batt level to this virtual device, and in the homey log, I got a nessage with the icon of the energy tab of the homey app (FYI this tab show the power but also the battery) and it's written something like (mine is in french): the battery of MyDevice is now OK (I think when it is green in the batt tab). Certainly, it exists the same message when the batt is becoming red but as I put a lot of the debug messages in the log, I've only few hours log which is displayed.

**Comment by DiedB** [comment]
The version with battery tab is v1.1.3, could you double check? I can see it in the App Store.

I want to have a way to disable those messages before this is released, it could get annoying quite fast.

**Comment by alechenne** [comment]
> The version with battery tab is v1.1.3, could you double check? I can see it in the App Store.
> 
> I want to have a way to disable those messages before this is released, it could get annoying quite fast.

Sorry for the delay. It was strange, I face some trouble and have to deinstall and reboot the Homey. Now I have the v1.1.3. I can read the measures. They are updated every 5 seconds. I saw also the battery tab with the percentage (2 digits). I can also see this battery percentage in the energy tab of the Homey tab and in the battery monitor app. For the battery, everything seems working well. 

Nevertheless, it seems there is a regression with the power: by the past it seems to me the power of the battery was available in the energy tab of the Homey tab. Am I wrong?

**Comment by DiedB** [comment]
Homey Energy was never implemented for this app - the reason being that the SDK does not provide enough flexibility to 'talk' to the Energy tab. For example, adding solar panels can only be done when the device is given the `solarpanel` class (which this device isn't), and adding home power consumption is not really possible either because the SDK doesn't allow specifying the capability that measures home power (for devices with multiple power measurement capabilities like this one).

**Comment by DiedB** [comment]
The app has been submitted for release!
