### ISSUE TITLE
More flows

### ISSUE THREAD

**Issue by Higgsy1990** [DiedB/Homey-TeslaEnergy#5]
Hi, is it possible to have more flows for example of the solar is producing X amount of power it could trigger me turning some appliances on ??

**Comment by DiedB** [comment]
Could you test https://homey.app/nl-nl/app/com.tesla.energy/Tesla-Energy/test/? Let me know if this works.

**Comment by Higgsy1990** [comment]
<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Bad Request</pre> </body> </htmlThat's the message I getSent from my iPhoneOn 5 Jul 2023, at 8:51 pm, Diederik Bakker ***@***.***> wrote:﻿
Could you test https://homey.app/nl-nl/app/com.tesla.energy/Tesla-Energy/test/? Let me know if this works.
