### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by alessioc01** [DiedB/Homey-TeslaEnergy#8]
Hi, I'm trying to add my Gateway Powerwall Version 23.4.2-1 fe55682a but after entering my username and password, I see the product 

![image](https://github.com/DiedB/Homey-TeslaEnergy/assets/58922250/fc775b1e-43ed-4c11-b9f8-38d81e5ac8c0)
and then this error...
![image](https://github.com/DiedB/Homey-TeslaEnergy/assets/58922250/18748cca-d80d-4c5d-ad7c-e7c988e845b5)

can you help me?
Thank you

**Comment by DiedB** [comment]
Let's discuss this in #6
